general:
  daemon: true
  sleep: 900
  state_path: state.db

credentials:
  - name: twitter-auth
    api_key: foo
    api_secret_key: bar
    access_token: foo
    access_token_secret: bar

sources:
  # Malspam watchers tweets (based on @soji256's list)
  - name: twitter-malspam-jp
    module: twitter
    credentials: twitter-auth
    owner_screen_name: soji256
    slug: malicious-site-report

  # PhishTank submissions (by @NaomiSuzuki_?)
  - name: phishtank-knack
    module: web
    url: https://www.phishtank.com/user_submissions.php?username=knack

  # PhishTank submissions (by @taku888infinity)
  - name: phishtank-nyantaku
    module: web
    url: https://www.phishtank.com/user_submissions.php?username=nyantaku

operators:
  - name: sqlite-db
    module: sqlite
    filename: artifacts.db
